name: Torrent Download with aria2c

on:
  workflow_dispatch:

jobs:
  download-torrent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v3

      - name: Install aria2
        run: sudo apt-get update && sudo apt-get install -y aria2

      - name: Download with aria2c (magnet link)
        run: |
          aria2c --dir=downloads --seed-time=0 "magnet:?xt=urn:btih:f90c43d21cf0a7eaa2fc583784f9341c18eeb30b&dn=%5BReducing%20Mosaic%5D%20ROYD-256%20%E3%81%9D%E3%81%AE%E5%A5%B3%E3%80%81%E6%B7%AB%E4%B9%B1%E3%81%AB%E3%81%A4%E3%81%8D%E2%94%81%20%E7%90%86%E6%80%A7%E3%81%8C%E5%90%B9%E3%81%8D%E9%A3%9B%E3%81%B6%E3%81%BB%E3%81%A9%E3%81%AE%E7%A9%B6%E6%A5%B5BODY%E4%BA%BA%E5%A6%BB%E3%81%A8%E3%81%AE%E4%B8%8D%E5%80%AB%E6%80%A7%E4%BA%A4%E3%80%82%20%E7%AB%B9%E5%86%85%E6%9C%89%E7%B4%80&tr=http%3A%2F%2Fsukebei.tracker.wf%3A8888%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce"

      # Or use .torrent file
      # - name: Download .torrent file
      #   run: wget -O file.torrent "https://example.com/some.torrent"
      #
      # - name: Download using .torrent
      #   run: aria2c --dir=downloads --seed-time=0 file.torrent

      - name: Show files
        run: ls -R downloads
